### PR TITLE
fix request.send callback argument error, can be called by await

### PR DESCRIPTION
**Pull request by allocwang**

### CODE REVIEW

**Comment by dashersw** [comment]
cote already works with async/await. Can you share an example that demonstrates this error?

**Comment by allocwang** [comment]
const cote = require('cote')({ redis: { host: 'localhost' } });
        const client = new cote.Requester({ name: 'Client' });
        setInterval( async () => {
            try{
                let time = await client.send({ type:'time' });
                console.log(time); // will not be executed
            }catch(err){
                console.log('err:'+err); // will print err:...
            }
        },1000);

**Comment by dashersw** [comment]
This depends on how you implement the responder. It should be utilising a promise, or should pass the error in the first parameter. I assume the responder here in this case is passing the actual answer in the first parameter, that's why it's interpreted as an error.

**Comment by allocwang** [comment]
Sorry! I should pass the err argument in the first place, right?

        const cote = require('cote')({ redis: { host: 'localhost' } });
        const timeService = new cote.Responder({ name: 'Time Service' });

        timeService.on('time', (req, res) => {
            console.log(req);
            let err=null;
            res(err,new Date());
        });

**Comment by dashersw** [comment]
Yes, that is the correct approach.

**Pull request closed without merging**
