### PR TITLE
Fix for leaking socket connections

### PR DESCRIPTION
**Pull request by dmitry-ilin**
Hi,

I made a small fix for leaking connections. It doesn't solve the issue entirely, but it helps to significantly slow down growing number of opened socket connections.

Could you review my changes and apply them?

Thanks.

### CODE REVIEW

**Comment by dmitry-ilin** [comment]
To debug opened connections you can use following code in terminal:

```lsof -i -n -P | grep "yourProcessName"``` to list all connections
and
```sof -i -n -P | grep "yourProcessName" | wc -l``` to get total number of connections

**Comment by dashersw** [comment]
Hello @dmitry-ilin! Thanks for the pull request. I've tried this with real world apps and the requester-responder pair within the examples folder; creating, destroying, and recreating requesters and responders. I couldn't reproduce the scenario where sockets leak. Can you share a reproduction scenario? Which OS are you running on?

By the way, the `obj` parameter passed to the `added` event handler is just a discovery message; it doesn't contain a `sock` property.

**Comment by dmitry-ilin** [comment]
I'm using OS X 10.11.2 and Ubuntu 15.10.
The issue happens after reconnection. 
For example assume we have couple of instances running on 2 physical machines. When one of them goes to sleep/halt and comes back the library reconnects these instances. Each reconnection leads to increasing number of used files. After certain amount of reconnections, system limitations are reached.

Recreating requesters/responders frees system resources.

I haven't check `obj` parameter passed to `added` event handler, but `obj` parameter passed to `removed` event handler has a `sock` property in some cases.

I'll try to reproduce the issue with the examples and write my results.

**Comment by dashersw** [comment]
Thanks for the explanation. I'll try that scenario and let you know!

**Comment by dashersw** [comment]
I was able to reproduce the issue. For reference, the reproduction scenario is as follows:

1) Run `examples/responder.js` on a machine A.
2) Run `examples/requester.js` on a machine B.
3) Sleep/pause machine B.
4) Wait until machine A detects disconnection.
5) Resume machine B.
6) Observe a new port/connection open on machine A.

**Comment by dashersw** [comment]
Hello @dmitry-ilin, I've investigated the issue thoroughly. `obj.sock` only exists for Subscribers and Responders; so it's enough to include those files. May I ask you to remove your additions from `Publisher.js` and `Requester.js`?

Additionally, you had mentioned that this doesn't solve the issue entirely. What scenarios are uncovered by this fix?

**Comment by dmitry-ilin** [comment]
Hello @dashersw !
I've removed my additions from `Requester.js` and `Publisher.js`. At this moment I cannot reproduce any other socket leaking issue using examples. I believe it could be related to environment or my app. I will monitor network connections and, if I'll find any uncovered scenario, I'll create another issue (or pull request, if I'll be lucky to solve it).

**Comment by dashersw** [comment]
Thanks a lot!

**Pull request merged**
